### PR TITLE
Resolve peer issues by forcing some upgrades

### PR DESCRIPTION
**Pull request by NullVoxPopuli**
Resolves: https://github.com/GavinJoyce/ember-headlessui/issues/160

### CODE REVIEW

**Review by dmcnamara-eng — APPROVED** [review]
Nice 👍

**Comment by dmcnamara-eng** [comment]
Not sure if it's my environment, but getting an error on `release-it --dry-run` :

> ERROR Could not infer "repo" from the "package.json" file.

**Comment by NullVoxPopuli** [comment]
hmm -- that's an issue with lerna-changelog -- it comes from here: https://github.com/lerna/lerna-changelog/blob/master/src/configuration.ts#L43

I'd place a breakpoint there in vscode's javascript debug terminal, if you want to see what's going wrong -- I gotta do some other stuff for now -- but feel free to push to this Pr

**Comment by NullVoxPopuli** [comment]
Another approach: https://github.com/embroider-build/addon-blueprint/pull/44/commits/c650db72b451b7ad3d802aa85d649ec60c7b1ea6

**Comment by NullVoxPopuli** [comment]
resolved by: https://github.com/GavinJoyce/ember-headlessui/pull/163

**Pull request closed without merging**
