### PR TITLE
[spike] try @embroider/test-setup

### PR DESCRIPTION
**Pull request by GavinJoyce**
trying https://github.com/embroider-build/embroider/blob/master/ADDON-AUTHOR-GUIDE.md#support-level-optimized-embroider-safe

### CODE REVIEW

**Comment by GavinJoyce** [comment]
Needs some work:

```
=== Scenario: embroider-optimized ==============================================

Successfully applied EMBROIDER_TEST_SETUP_OPTIONS=optimized
Building
Environment: test
building... 
Building into /tmp/embroider/07f630/tests/dummy
WARNING: Your build is slower because some babel plugins are non-serializable
cleaning up
cleaning up...
Build Error (PackagerRunner) in ../../components/menu/item-element.hbs

Module Error (from /home/runner/work/ember-headlessui/ember-headlessui/node_modules/@embroider/webpack/src/webpack-hbs-loader.js):
Unsafe dynamic component: cannot statically analyze this expression in $TMPDIR/embroider/07f630/components/menu/item-element.hbs
```

**Comment by GavinJoyce** [comment]
https://github.com/tildeio/ember-element-helper/pull/34 should address ^ when it lands

**Comment by NullVoxPopuli** [comment]
This is already in use and can be closed?

**Comment by GavinJoyce** [comment]
👍

**Pull request closed without merging**
